---
- name: Tool per cracking di password e hash
  hosts: "{{ target }}"
  become: true

  tasks:
    - name: Installa tool password da apt (Kali)
      ansible.builtin.apt:
        name:
          - john
          - hydra
          - hashcat
          - medusa
          - crunch
          - fcrackzip
          - pdfcrack
          - cewl
        state: present
        update_cache: true

    - name: Estrai rockyou.txt se ancora compresso
      ansible.builtin.command:
        cmd: gunzip -k /usr/share/wordlists/rockyou.txt.gz
        creates: /usr/share/wordlists/rockyou.txt
      ignore_errors: true
